version: "3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dY0iR2gA9iY9oM7g
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: dY0iR2gA9iY9oM7g

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: dY0iR2gA9iY9oM7g
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
